spending_dbt:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: spending-data-analysis         # your GCP project ID
      dataset: spending_dev                   # dbt models go here (dev)
      keyfile: "{{ env_var('GOOGLE_APPLICATION_CREDENTIALS') }}"
      location: asia-northeast1               # adjust if needed
      threads: 4
      timeout_seconds: 300
      priority: interactive
      retries: 1

    prod:
      type: bigquery
      method: service-account
      project: spending-data-analysis
      dataset: spending_prod                  # dbt models go here (prod)
      keyfile: "{{ env_var('GOOGLE_APPLICATION_CREDENTIALS') }}"
      location: asia-northeast1
      threads: 4
      timeout_seconds: 300
      priority: interactive
      retries: 1
